# Generated by Django 3.2.7 on 2021-09-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210922_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_day',
            new_name='birthday',
        ),
    ]
