# Generated by Django 3.2.7 on 2021-09-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_birth_day_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='street_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
