# Generated by Django 3.2.7 on 2021-09-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='youtube',
            new_name='skype',
        ),
    ]
