# Generated by Django 3.2.7 on 2021-09-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_social_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='light theme', max_length=15),
        ),
    ]
