# Generated by Django 3.2.7 on 2021-09-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
