# Generated by Django 3.2.7 on 2021-09-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_multiplechoice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoice',
            name='question',
            field=models.CharField(max_length=100, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='multiplechoiceanswer',
            name='answer',
            field=models.CharField(max_length=100, verbose_name='answer'),
        ),
    ]
